# Generated by Django 4.1.6 on 2023-02-22 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('assetid', models.AutoField(db_column='AssetID', primary_key=True, serialize=False)),
                ('assetname', models.TextField(db_column='AssetName', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Countermeasures',
            fields=[
                ('countermeasureid', models.AutoField(db_column='CounterMeasureID', primary_key=True, serialize=False)),
                ('countermeasurename', models.TextField(db_column='CounterMeasureName', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Threats',
            fields=[
                ('threatid', models.AutoField(db_column='ThreatID', primary_key=True, serialize=False)),
                ('threatname', models.TextField(db_column='ThreatName', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=255)),
                ('type', models.CharField(choices=[('User', 'User'), ('Expert', 'Expert')], default='User', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CountermeasureDescriptions',
            fields=[
                ('countermeasureid', models.OneToOneField(db_column='CounterMeasureID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='skms.countermeasures')),
                ('countermeasuredescription', models.TextField(db_column='CounterMeasureDescription')),
            ],
        ),
        migrations.CreateModel(
            name='ThreatDescriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threatdescription', models.TextField(db_column='ThreatDescription')),
                ('threatid', models.OneToOneField(db_column='ThreatID', on_delete=django.db.models.deletion.DO_NOTHING, to='skms.threats')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('likes', models.IntegerField(default=0)),
                ('subject', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comments', models.ManyToManyField(related_name='post_comments', to='skms.comment')),
                ('subscriptions', models.ManyToManyField(related_name='subscribed_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='skms.post'),
        ),
    ]
